export { default as Testimonials } from "./testimonials"
export { default as HeroSection } from "./hero-section"
export { default as GetInTouch } from "./get-in-touch"
export { default as Service1 } from "./service1"
export { default as Service2 } from "./service2"
export { default as GridServices } from "./grid-services"
export { default as Features } from "./features"
