export { default as Services } from "./services"
export { default as GetInTouch } from "./get-in-touch"
export { default as Testimonials } from "./testimonials"
export { default as ShowcaseSolutions } from "./showcase-solutions"
export { default as Slider } from "./slider"
