export { default as LandingPage } from "./landingPage"
export { default as CommercialCleaningPage } from "./commercialCleaningCopyPage"
export { default as BucketsProPage } from "./bucketsProPage"
export { default as ContactPage } from "./contactPage"
export { default as PricingPage } from "./pricingPage"
